[versions]
# Build Tools
agp = "8.13.2"
minSdk = "24"
targetSdk = "36"
compileSdk = "36"
java = "17"

# Kotlin
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization-json = "1.9.0"

# AndroidX
androidx-core-ktx = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.6"

# Google
androidx-credentials = "1.5.0"
googleid = "1.1.1"

# Compose
compose-multiplatform = "1.9.3"

# Network
ktor = "3.3.3"

# Koin
koin = "4.1.1"

# BuildKonfig
buildkonfig = "0.17.1"

# Supabase
supabase = "3.2.6"

# Ktlint
ktlint = "14.0.1"

# Test
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
androidx-test-runner = "1.7.0"
androidx-test-core = "1.7.0"
androidx-espresso = "3.7.0"

[libraries]
# Gradle Plugins
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# Google Credential Manager
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# Supabase
supabase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabase" }
supabase-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt" }
supabase-auth = { group = "io.github.jan-tennert.supabase", name = "auth-kt" }
supabase-realtime = { group = "io.github.jan-tennert.supabase", name = "realtime-kt" }

# Test
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

[bundles]
androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-activity-compose",
]

androidx-lifecycle = [
    "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-runtime-compose",
]

credential-manager = [
    "androidx-credentials",
    "googleid",
]

kotlinx = [
    "kotlinx-coroutines-core",
    "kotlinx-serialization-json",
]

ktor-common = [
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
]

koin = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel",
]

supabase = [
    "supabase-auth",
    "supabase-postgrest",
    "supabase-realtime"
]

test-unit = [
    "junit",
    "kotlin-test",
    "kotlin-test-junit",
]

test-android = [
    "androidx-test-ext-junit",
    "androidx-test-runner",
    "androidx-test-core",
    "androidx-espresso-core",
]

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Kotlin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Compose
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

# BuildKonfig
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }

# Ktlint
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
